### ISSUE TITLE
Confusing "share your email" app permission option

### ISSUE THREAD

**Issue by mbland** [18F/myusa-ux#15]
I've had a few users report recently that they failed to log into the [Hub](https://github.com/18F/hub) for the first time after being presented with screens like this (with the email address blotted out):

![myusa-permissions](https://cloud.githubusercontent.com/assets/301547/8552022/43e540ec-24a8-11e5-955c-c8f010842c6e.png)

Apparently folks don't pick up on the fact that they need to click the "share your email" button before clicking _Allow_, which causes the Hub's authentication to fail (using [bitly/oauth2_proxy](https://github.com/bitly/oauth2_proxy)).

Thoughts on how to make this easier for new users to follow?

**Comment by mbland** [comment]
cc: @emaland

**Comment by esgoodman** [comment]
Thanks for the info. It comes at a good time. We are close to rolling out a
new version of the whole flow -- it's been a long process and we are still
discovering new issues. I think the simplest fix right now is to make the
email sharing opt out.

Work for you?

**Comment by mbland** [comment]
Seems like that might work in the short term, yeah. Thanks!

**Comment by esgoodman** [comment]
We are also working on getting a test app up on staging so that our work-in-progress sign-in is testable without setting up the whole MyUSA app on your own machine. @yozlet is on the case.

**Comment by esgoodman** [comment]
I think this might be something you can do solo, @harrisj?

**Comment by mbland** [comment]
FYI, as to why I looped in @emaland: He was the most recent person who hit the issue trying to access the Hub, and I just wanted him to know I was doing due diligence to follow up. But there was at least one other person who hit the same issue before.

**Comment by juliasolorzano** [comment]
Fixed here: https://github.com/18F/myusa/pull/701
