### ISSUE TITLE
How much should we/can we customize content? 

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa-ux#5]
We initially wrote copy, particularly help text, that could cover many different applications. As people went through the sign-in flow, we discovered that the copy often raised more questions than it answered. As one participant said, seeing the help text _opened a can of worms_. 

For example, one participant's response to the toggles was: "Can I opt out?." Her first impulse was to hit "cancel." After reading the help text, she'd still hit "cancel." For her, the information is "not specific -- share information to whom? from this website? to other agencies?"

This participant's reaction, though stronger than many, was not unusual. Given pervasive spam, intrusive emails, keyword generated advertising, and cookie-enabled tracking, it's not surprising that research participants are wary of clicking "accept." 

Customizing content per application, especially help text, might help us [earn the trust](https://github.com/18F/myusa-ux/blob/master/research/memos/design-principles.md#trust-must-be-earned) of first-time users by making specific and concrete promises. However, it's extra effort. 

We've talked about doing a [Mad-Libs-style content generator](http://glusman.com/leanexample/start.html) for agencies, but the first question to think about is....how much should we customize the content for MyUSA app first-time sign-in?

**Comment by esgoodman** [comment]
After having a conversation with @kategarklavs today, the tentative plan is to write custom copy at least for the permissions screen for all our partners. Right now, we have few enough integrators that it shouldn't be too big of a time commitment. If/when it does start to take too much time, we can automate the process a little more.

**Comment by kategarklavs** [comment]
+1 to @esgoodman's plan. Once the # of integrators becomes too great to allow us to write custom copy for each, we can introduce our copy playbook (or analogous tool) to help integrator reps write their own copy.

**Comment by kategarklavs** [comment]
@esgoodman Incidentally, what is the timeline for this? (I briefly touched on it during our last sprint planning meeting, but I'm not sure a deadline was set.)

**Comment by esgoodman** [comment]
@yozlet has confirmed that per-app customized content will require some changes to MyUSA's backend. As per @yozlet, this is totally doable but can't be started until we get past ATO. The MVP of this feature will probably be a manual database update we do on behalf of each integrator. Later, we can put in some UI for it if there is enough need. I am going to file an issue in the main repo so that it can be added to the development priorities.

**Comment by esgoodman** [comment]
See https://github.com/18F/myusa/issues/644.
