### ISSUE TITLE
How do we balance convenience and control? 

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa-ux#7]
There is a predictable yet difficult to resolve tension between [making consent meaningful](https://github.com/18F/myusa-ux/blob/master/research/memos/design-principles.md#consent) and [not getting in people's way](https://github.com/18F/myusa-ux/blob/master/research/memos/design-principles.md#block). **The more information we give people and the more we ask them to make decisions, the more we get between them and the job they want to get done.**

**Comment by esgoodman** [comment]
It manifests right now most obviously in the sign-in flow. 

![screen shot 2015-04-08 at 3 44 45 pm](https://cloud.githubusercontent.com/assets/10067318/7263325/77403b4a-e835-11e4-8e97-fdc9ef2a3756.png)

Per-item permissions slow people down. [Convenience optimizers](https://github.com/18F/myusa-ux/blob/master/research/memos/users.md) may not even look at them. Each separate permission gives [privacy defenders](https://github.com/18F/myusa-ux/blob/master/research/memos/users.md) and [privacy sensitives] more to worry about.

**Comment by esgoodman** [comment]
Facebook has been doing per-item permissions for more than a year, with [reasonably good results](http://www.businessinsider.com/facebook-login-updates-for-more-privacy-2015-4). If they can make it work, so can we. 

Here's an [example](http://www.adweek.com/socialtimes/wp-content/uploads/sites/2/2014/04/login1.png) of how FB does it.

**Comment by kategarklavs** [comment]
@esgoodman: Could we offer a single name field instead of first name/last name? That would reduce the current # of permissions-related fields by a third.

**Comment by yozlet** [comment]
+1 on a single name field if we can do it, because it takes care of [some of the typical name problems](http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/). However, given the number of govt forms that require separate first and last name entry, we may not be able to get away with this. (Or we could just make it the RP's problem)

**Comment by esgoodman** [comment]
Closed by popular demand (or at least, silence) after the coworking meeting. We are agreed to keep going with the per-item permissions.
